project:
  type: website

website:
  title: "DataRchive"
  site-url: "https://example.com"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  sidebar: false

formats:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

listing:
  contents: posts
  sort: "date desc"
  type: default
