[build]
command = """
    curl -LO https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.554/quarto-1.4.554-linux-amd64.tar.gz
    tar -xzf quarto-1.4.554-linux-amd64.tar.gz
    export PATH=$PWD/quarto-1.4.554/bin:$PATH
    quarto render
  """
publish = "_site"